export class AppImages {
  static APP_MAIN_ICON = require('../assets/images/app_main_icon.png');
  static BACK_ICON = require('../assets/images/round_back_icon.png');
  static LOGIN_ICON = require('../assets/images/login_icon.png');
  static KEY_ICON = require('../assets/images/key_icon.png');
  static PHONE_ICON = require('../assets/images/phone_icon.png');
  static USER_PHONE_ICON = require('../assets/images/user_phone_icon.png');
  static PHONE_SMALL_ICON = require('../assets/images/phone_small_icon.png');
  static KEY_SMALL_ICON = require('../assets/images/key_small_icon.png');
  static EYE_OPEN = require('../assets/images/eye_open.png');
  static EYE_CLOSE = require('../assets/images/eye_close.png');
  static PAYMENT_ICON=require('../assets/images/payment_icon.png')
  static USER_LOGIN_ICON=require('../assets/images/user_login_icon.png')
  static USER_KEY_ICON = require('../assets/images/user_key_icon.png');
  static LOCATION_ICON = require('../assets/images/location_icon.png');
  static DROP_DOWN_ICON = require('../assets/images/drop_down_icon.png');
  static LOGOUT_ICON = require('../assets/images/logout_icon.png');
  static ABOUT_US_ICON=require('../assets/images/about_us_icon.png');
  static SEARCH_ICON=require('../assets/images/seacrh_icon.png');
  static STATICS_ICON=require('../assets/images/statics_icon.png');
  static FAMILY_MEMBER_ICON=require('../assets/images/family_member_icon.png');
  static BUSSINESS_ICON=require('../assets/images/Businness_icon.png');
  static VILLAGE_ICON=require('../assets/images/village_member_icon.png');
  static NEWS_ICON=require('../assets/images/news_icon.png');
  static FORM_ICON=require('../assets/images/form_icon.png');
  static CONTACT_US_ICON=require('../assets/images/contact_us_icon.png');
  static ROUND_BACK_ICON=require('../assets/images/round_back_icon.png');
  static CALL_ICON=require('../assets/images/call_icon.png');
  static BUTTON_ICON=require('../assets/images/button_arrow.png');
  static SMALL_MAN_IMAGE=require('../assets/images/small_man_image.png')
  static ICON_EDIT=require('../assets/images/edit_icon.png')
  static ICON_DELETE=require('../assets/images/delete_icon.png')
  static MEMBER_IMAGE=require('../assets/images/member_image.png');
  static DROP_UP_ICON=require('../assets/images/drop_up_image.png');
  static DROP_DOWN_GRAY=require('../assets/images/drop_down_gray.png')
  static ICON_TEST_VILLAGE=require('../assets/images/icon_test_village.png')
  static NEWS_FILE_ICON=require('../assets/images/news_file_icon.png');
  static ICON_PDF_LIST=require('../assets/images/icon_pdf_list.png')
  static EYE_ICON=require('../assets/images/eye_icon.png');
  static ICON_UNCHECK=require('../assets/images/icon_uncheck.png');
  static NAME_SMALL_ICON=require('../assets/images/name_small_icon.png');
  static WHATSAPP_ICON=require('../assets/images/whatsapp_icon.png');
  static CIRCLE_CALL_ICON=require('../assets/images/circle_call_icon.png');
  static IMP_LINKS_ICON=require('../assets/images/imp_link.png');
  static SOCIAL_HELP_ICON=require('../assets/images/social_help.png');
  static FEEDBACK_ICON=require('../assets/images/feedback.png');
}
